### ISSUE TITLE
Animate Process - R Studio - Viewer

### ISSUE THREAD

**Issue by dupadhyaya** [bupaverse/processanimateR#29]
When I try to animate_process(anyevent), I expect it to run in R Studio Viewer also as it was running earlier. After my update to R 4.0 / or otherwise (which I cannot remember correctly), viewer is not displaying animated process... However when I run the command without R Studio (Simple R interface), process can be seen in URL. I am able to save the video, but unable to see inside the Viewer.
I think some firewall or block by R Studio app or other issue ?
Can someone guide please. Unable to diagnose.

**Comment by dupadhyaya** [comment]
Just to update on this issue raised by me. This issue started when I update R to latest version 4.0.0  . Today I updated R Studio to latest version Version 1.3.959 which rectified the issue. It could be because be Viewer properties

**Comment by fmannhardt** [comment]
Thanks for letting me know and sorry for not having the time to look into this.
